
baseurl: ""
url: "http://thin-languages.github.io/more"


name: More
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: ['jekyll-paginate', 'rouge']